return {
	corpending = {
		acceleration = 0.0552,
		brakerate = 0.43125,
		buildcostenergy = 1000000,
		buildcostmetal = 40000,
		buildpic = "CORJUGG.DDS",
		buildtime = 120000,
		canmove = true,
		canmanualfire = true,
		category = "BOT WEAPON ALL NOTSUB NOTAIR NOTHOVER SURFACE",
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "90 80 90",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		explodeas = "juggernaut",
		footprintx = 5,
		footprintz = 5,
		idleautoheal = 40,
		idletime = 1800,
		mass = 3000000,
		maxdamage = 500000,
		maxslope = 14,
		maxvelocity = 0.55,
		maxwaterdepth = 12,
		movementclass = "HBOT5",
		nochasecategory = "VTOL",
		objectname = "Units/CORPENDING.s3o",
		power = 114200, --compensation for XP rank with high AoE weapons
		pushresistant = true,
		radardistance = 1000,
		radaremitheight = 100,
		script = "Units/CORPENDING.cob",
		seismicsignature = 0,
		selfdestructas = "juggernautSelfd",
		sightdistance = 1000,
		turninplace = true,
		turninplaceanglelimit = 90,
		turninplacespeedlimit = 0.363,
		turnrate = 125.35,
		customparams = {
			unitgroup = 'weapon',
			customrange = 435,
			model_author = "FireStorm",
			normaltex = "unittextures/cor_normal.dds",
			paralyzemultiplier = 0,
			subfolder = "corgantry",
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-0.35619354248 -4.26102086182 -1.35372924805",
				collisionvolumescales = "105.219192505 63.5703582764 119.881469727",
				collisionvolumetype = "Box",
				damage = 27000,
				energy = 0,
				featuredead = "HEAP",
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 8,
				hitdensity = 100,
				metal = 13959,
				object = "Units/corjugg_dead.s3o",
				reclaimable = true,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 13500,
				energy = 0,
				featurereclamate = "SMUDGE01",
				footprintx = 2,
				footprintz = 2,
				height = 2,
				hitdensity = 100,
				metal = 2793,
				object = "Units/cor4X4A.s3o",
				reclaimable = true,
				resurrectable = 0,
				seqnamereclamate = "TREE1RECLAMATE",
				world = "All Worlds",
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-huge",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "doom",
			},
			select = {
				[1] = "doom",
			},
		},
		weapondefs = {
			juggernaut_fire = {
				areaofeffect = 65,
				avoidfeature = false,
				bouncerebound = 0,
				cegtag = "gausscannonprojectile",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:burnblackbig",
				firestarter = 100,
				firesubmersed = false,
				groundbounce = true,
				gravityaffected = true,
				impulseboost = 0,
				impulsefactor = 0,
				intensity = 4,
				name = "GaussCannon",
				noexplode = true,
				noselfdamage = true,
				range = 590,
				reloadtime = 4,
				rgbcolor = "1 0.8 0.17",
				size = 6.5,
				soundhit = "xplomed2",
				soundhitwet = "sizzlexs",
				soundstart = "krogun1",
				soundhitvolume = 32,
				soundtrigger = true,
				turret = true,
				waterweapon = false,
				weapontype = "DGun",
				weaponvelocity = 520,
				damage = {
					default = 1200,
				},
			},
			disintegrator = {
				areaofeffect = 80,
				avoidfeature = false,
				avoidfriendly = false,
				avoidground = false,
				bouncerebound = 0,
				cegtag = "dgunprojectile",
				commandfire = true,
				craterboost = 1,
				cratermult = 0.30,
				edgeeffectiveness = 0.15,
				energypershot = 5000,
				explosiongenerator = "custom:expldgun",
				firestarter = 100,
				firesubmersed = false,
				groundbounce = true,
				impulseboost = 0,
				impulsefactor = 0,
				name = "Disintegrator",
				noexplode = true,
				noselfdamage = true,
				range = 700,
				reloadtime = 0.4,
				soundhit = "xplomas2s",
				soundhitwet = "sizzlexs",
				soundstart = "disigun1",
				soundhitvolume = 45,
				soundstartvolume = 110,
				soundtrigger = true,
				tolerance = 10000,
				turret = true,
				waterweapon = true,
				weapontimer = 4.2,
				weapontype = "DGun",
				weaponvelocity = 520,
				damage = {
					default = 99999,
					scavboss = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "DISINTEGRATOR",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "JUGGERNAUT_FIRE",
				onlytargetcategory = "NOTSUB",
				maindir = "-1 0 4",
			},
			[3] = {
				badtargetcategory = "VTOL GROUNDSCOUT",
				def = "JUGGERNAUT_FIRE",
				onlytargetcategory = "NOTSUB",
				maindir = "-1 0 4",
			},
		},
	},
}
